### ISSUE TITLE
Non-Branch Links are not detected by the plugin

### ISSUE THREAD

**Issue by suzon** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#160]
I’ve implemented `NonBranchLinkHandler()` like below, which is detected into iPhone/iPad but it is not detected into Android phones/tab.  Note: I’m using cordova-ionic-phonegap-branch-deep-linking version: 2.1.6 
```
window.NonBranchLinkHandler = function (data) {
   console.info(data);
   topic.publish('xyz', data);
};
```

I did not found any exception to show on post!
Community ref → https://mobilegrowth.org/questions/question/non-branch-links-are-not-detected-by-the-plugin/

**Comment by aaustin** [comment]
Hey @suzon - That's strange. I swear I fixed this in the latest release. I will investigate first thing tomorrow.

**Comment by aaustin** [comment]
@suzon - please review the PR I just made!

**Comment by suzon** [comment]
@aaustin - yes! this fix is working for me. Thank for quick fixing.

**Comment by suzon** [comment]
@aaustin - yes! this fix is working for me. Thank for quick fixing.

**Comment by malua** [comment]
Still not working for me. 
the string sent from `out = String.format("NonBranchLinkHandler(\"%s\")", message.toString());` has this extra `""` around the parameter object compared to the `out = String.format("DeepLinkHandler(%s)", referringParams.toString());`.

the javascript `eval()` method in cordova.js which is executing the output from `webView.sendJavascript(out);` is throwing an "uncaught syntaxerror: missing ) after argument list"

so the string looks like this: 

> NonBranchLinkHandler("{"error":"Not a Branch link!","url":"myapp:\/\/subsite\/86"}")

when i change it in runtime to:

> NonBranchLinkHandler({"error":"Not a Branch link!","url":"myapp:\/\/subsite\/86"})

the eval() method doesnt throw an error and NonBranchLinkHandler gets called properly.

**Comment by aaustin** [comment]
Thanks for the catch and suggested fix Malua. I'm merging this fellow in: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/pull/165
