### ISSUE TITLE
Hook is not working

### ISSUE THREAD

**Issue by paulstelzer** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#529]
I do not know why, but the Branch Cordova Plugin will not be added to the app (I am using Cordova 8.1.2 / Cordova-Android 7.1.4). After removing the following hook from plugin.xml it works:

`<hook src="src/scripts/hooks/beforePluginInstall.js" type="before_plugin_install" />`

**Comment by chrishanyu** [comment]
Having the same issue.

**Comment by christoph-bessei** [comment]
Related pull request: #521 
Version 3.1.0 seems to work fine.

**Comment by rj-david** [comment]
I tried 3.1.3, 3.1.0, and 3.0.1 and no build is working. All builds hangs after

> Resolving module name for q => q

**Comment by deliverymanager** [comment]
+1 The plugin is not added in the platform, just in the project.

**Comment by paulstelzer** [comment]
I wrote a PR (#527) that removes the cocoapods dependency (something that is directly integrated in cordova ios) and removed the hook, so it's working. You can test it by install https://www.npmjs.com/package/innomobile-branch-cordova-sdk (just replace `branch-cordova-sdk` with `innomobile-branch-cordova-sdk` in your config.xml if you want to test it - or wait until the Branch team insert a fix)

**Comment by rj-david** [comment]
@aaaronlopez, just tagging you directly since this is an urgent issue. Nobody can build successfully because of this issue.

**Comment by deliverymanager** [comment]
@paulstelzer I have just tested your forked plugin innomobile-branch-cordova-sdk
but the Branch library is not defined inside the project.
It does not exist in the window global variable.
The plugin is inserted though in the cordova_plugins.js

**Comment by paulstelzer** [comment]
@deliverymanager See #533

Yeah, something Cordova iOS related - Just run `pod install` inside `<yourapp>/platforms/ios` or run it inside Xcode.

The Pod wasn't installed correctly (https://guides.cocoapods.org/using/pod-install-vs-update.html). Afterwards it should work

**Comment by deliverymanager** [comment]
I am testing on Android platform

**Comment by paulstelzer** [comment]
`npm install innomobile-branch-cordova-sdk@latest`

Inside config.xml:
`<plugin name="innomobile-branch-cordova-sdk" spec="^3.1.5"/>`

Instead of `<plugin name="innomobile-branch-cordova-sdk" spec="^3.1.2"/>`

Important: You have to use 3.1.5 (the versions before are broking like branch-cordova-sdk)

**Comment by deliverymanager** [comment]
Yes I confirm installing 3.1.5

**Comment by deliverymanager** [comment]
Yes I confirm everything.
The only difference of course is the PACKAGE_NAME which is the one I am using.
Everything else is the same.

**Comment by paulstelzer** [comment]
Then it should work :D

**Comment by deliverymanager** [comment]
Something might have been stuck.
It does work now.

**Comment by deliverymanager** [comment]
Is there any problem if I publish the app with your plugin and then republish with the original once it is corrected too?

**Comment by paulstelzer** [comment]
No, if branch updated it, just replace Inside config.xml from

`<plugin name="innomobile-branch-cordova-sdk" spec="^3.1.5"/>`

to

 `<plugin name="branch-cordova-sdk" spec="^3.1.3"/>`

My is just a fork of the Branch Plugin (only with the fix)

**Comment by deliverymanager** [comment]
ok thank you!

**Comment by aaaronlopez** [comment]
hello all, we tested a change with 3.1.4 that did not appear to resolve the issue. We modified the plugin hooks and released a beta candidate, `3.1.5-beta.0` to unblock most folks.  Can anyone that tests it out please let us know whether it resolves this issue? Separately, we are testing #533 to use Cocoapods directly.

**Comment by ctolkien** [comment]
Just wanted to chime in that we are also impacted on this.

**Comment by rj-david** [comment]
@aaaronlopez, confirming that 3.1.5-beta.0 is working for both Android and iOS builds

**Comment by sequoiaat** [comment]
We hope release 3.1.5 solved this issue for everyone
